Repository ember-cli/broccoli-terser-sourcemap, pull requests merged in 2020-09, with the labels that each got.

#241 Lowest supported node version is 10
  .travis.yml
  package.json
Labels: breaking

#237 Update to terser v5
  index.js
  lib/process-file.js
  package.json
  test/__snapshots__/test.js.snap
  test/test.js
  yarn.lock
Labels: breaking

#244 Remove Babel transpilation during tests.
  .babelrc
  package.json
Labels: internal

#246 Remove Travis CI setup.
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#247 Add release automation and documentation.
  CHANGELOG.md
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#243 Refactor to native class.
  README.md
  index.js
  package.json
  test/test.js
  yarn.lock
Labels: breaking

#250 Rename to broccoli-terser-sourcemap.
  README.md
  index.js
  lib/get-sourcemap-content.js
  lib/process-file.js
  package.json
  test/__snapshots__/test.js.snap
  test/test.js
Labels: enhancement
